import React, { useState, useEffect, useRef } from 'react';
import { QrCode, Download, LogOut, Calendar, MapPin, Clock, User, Hash, Building, Award, ShieldCheck, ExternalLink } from 'lucide-react';
import { motion } from 'framer-motion';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { supabase } from '../lib/supabase';

export default function StudentCard() {
  const [user, setUser] = useState(null);
  const [reg, setReg] = useState(null);
  const [schedule, setSchedule] = useState(null);
  const [loading, setLoading] = useState(true);
  const [qrUrl, setQrUrl] = useState('');
  const cardRef = useRef(null);

  useEffect(() => {
    const init = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) { window.location.href = '/login'; return; }
      setUser(session.user);

      const { data: regData } = await supabase
        .from('registration_requests')
        .select('*, competitions(title, category, color, fee)')
        .eq('email', session.user.email)
        .eq('status', 'approved')
        .single();

      if (regData) {
        setReg(regData);
        if (regData.competition_id) {
          const { data: schedData } = await supabase
            .from('schedules')
            .select('*, rooms(name, location), time_slots(label, start_time, end_time, event_date)')
            .eq('competition_id', regData.competition_id)
            .single();
          setSchedule(schedData);
        }

        const qrData = JSON.stringify({
          id: regData.id,
          name: regData.student_name,
          email: regData.email,
          competition: regData.competitions?.title,
          reg_no: regData.reg_number,
        });
        const encoded = encodeURIComponent(qrData);
        setQrUrl(`https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encoded}&bgcolor=ffffff&color=4f46e5&margin=5`);
      }
      setLoading(false);
    };
    init();
  }, []);

  const logout = async () => {
    await supabase.auth.signOut();
    window.location.href = '/login';
  };

  const downloadCard = () => {
    if (!cardRef.current) return;
    
    // We get the HTML, but we need to ensure the print window has all necessary styles
    // to match the screen version exactly.
    const printContent = cardRef.current.innerHTML;
    const compColor = reg?.competitions?.color || '#4f46e5';
    
    const w = window.open('', '_blank');
    w.document.write(`
      <html>
        <head>
          <title>VSpark Digital Pass - ${reg?.student_name}</title>
          <link href="https://fonts.googleapis.com/css2?family=Sora:wght@400;600;700;800&display=swap" rel="stylesheet">
          <script src="https://cdn.tailwindcss.com"></script>
          <script>
            tailwind.config = {
              theme: {
                extend: {
                  colors: {
                    primary: { 50: '#eff6ff', 100: '#dbeafe', 500: '#3b82f6', 600: '#2563eb', 700: '#1d4ed8' }
                  },
                  fontFamily: {
                    sora: ['Sora', 'sans-serif'],
                  }
                }
              }
            }
          </script>
          <style>
            @page { size: auto; margin: 10mm; }
            body { 
              -webkit-print-color-adjust: exact !important; 
              print-color-adjust: exact !important;
              background-color: #f9fafb;
              font-family: 'Sora', sans-serif;
            }
            .card-wrap {
              width: 100%;
              max-width: 500px;
              margin: 0 auto;
            }
          </style>
        </head>
        <body>
          <div class="card-wrap py-10">
            <div class="bg-white rounded-[2.5rem] border border-gray-100 shadow-2xl relative overflow-hidden flex flex-col" style="border-left: 8px solid ${compColor}">
              ${printContent}
            </div>
            <div class="mt-8 text-center text-gray-400 text-[10px] font-bold uppercase tracking-widest">
              Generated by VSpark Digital System • Official Participation Pass
            </div>
          </div>
          <script>
            window.onload = () => {
              // Small delay to ensure Tailwind JIT and fonts are ready
              setTimeout(() => {
                window.print();
                // Close window after print dialog closes (optional, but cleaner)
                // window.close(); 
              }, 1000);
            };
          </script>
        </body>
      </html>
    `);
    w.document.close();
  };

  if (loading) return (
    <div className="min-h-screen bg-gray-50 flex flex-col font-sora">
      <Navbar />
      <div className="flex-1 flex flex-col items-center justify-center p-6 text-center">
        <div className="w-12 h-12 border-4 border-primary-100 border-t-primary-500 rounded-full animate-spin mb-4" />
        <p className="text-gray-400 font-medium">Generating your pass...</p>
      </div>
      <Footer />
    </div>
  );

  if (!reg) return (
    <div className="min-h-screen bg-gray-50 flex flex-col font-sora">
      <Navbar />
      <div className="flex-1 flex flex-col items-center justify-center p-6 pt-32 pb-24 text-center">
        <div className="max-w-md bg-white p-10 rounded-3xl border border-gray-100 shadow-sm">
          <div className="w-20 h-20 bg-gray-50 rounded-full flex items-center justify-center mx-auto mb-6 text-gray-300">
            <QrCode size={40} />
          </div>
          <h2 className="font-black text-2xl text-gray-900 mb-2">No Active Pass</h2>
          <p className="text-gray-500 mb-8 leading-relaxed">
            Your registration is either pending verification or you haven't registered yet. Digital cards are only available for approved participants.
          </p>
          <div className="flex flex-col gap-3">
            <Link to="/register" className="btn-primary justify-center font-bold">Register Now</Link>
            <button onClick={logout} className="text-gray-400 font-bold text-sm hover:text-red-500 transition-colors">Sign Out</button>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );

  const compColor = reg.competitions?.color || '#4f46e5';

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col font-sora">
      <Navbar />
      
      <section className="flex-1 pt-32 pb-24 px-4 flex flex-col items-center">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-center mb-10">
          <span className="section-tag mb-4 shadow-sm border-primary-100">Official Participation Pass</span>
          <h1 className="font-black text-4xl md:text-5xl text-gray-900 mb-3 tracking-tight">Your Digital Pass</h1>
          <p className="text-gray-500 max-w-sm mx-auto font-medium">Please show this QR code at the event check-in desk.</p>
        </motion.div>

        {/* ── DIGITAL CARD ── */}
        <div className="w-full max-w-lg mb-10">
          <motion.div 
            initial={{ opacity: 0, scale: 0.98 }} animate={{ opacity: 1, scale: 1 }}
            className="bg-white rounded-[2.5rem] border border-gray-100 shadow-2xl relative overflow-hidden flex flex-col"
            style={{ borderLeft: `8px solid ${compColor}` }}
          >
            {/* We will read THIS inner content for printing */}
            <div ref={cardRef} className="flex flex-col w-full h-full">
              {/* Header */}
              <div className="p-8 pb-4 flex justify-between items-start border-b border-gray-50">
                <div>
                  <h2 className="font-black text-2xl tracking-tighter text-gray-900 leading-none">
                    V<span className="text-primary-600">SPARK</span>
                  </h2>
                  <p className="text-[9px] font-black text-gray-400 tracking-[0.2em] uppercase mt-1.5">National Competition Pass</p>
                </div>
                <div className="flex flex-col items-end">
                  <span className="px-3 py-1 bg-primary-50 text-primary-600 border border-primary-100 rounded-full text-[10px] font-black tracking-widest uppercase">
                    PARTICIPANT
                  </span>
                  <span className="text-gray-300 font-mono text-xs mt-2">#{String(reg.id).padStart(4, '0')}</span>
                </div>
              </div>

              {/* Body */}
              <div className="p-8 flex flex-col md:flex-row gap-8">
                <div className="flex-1 space-y-5">
                  <div>
                    <label className="text-[10px] font-black text-gray-400 uppercase tracking-widest block mb-1">Participant Name</label>
                    <p className="font-black text-2xl text-gray-900 leading-tight">{reg.student_name}</p>
                  </div>

                  <div className="grid grid-cols-1 gap-y-4 pt-2">
                    <div className="flex items-start gap-3">
                      <Hash size={14} className="text-primary-500 mt-0.5" />
                      <div>
                        <p className="text-[9px] font-bold text-gray-400 uppercase tracking-widest">Reg Number</p>
                        <p className="text-sm font-bold text-gray-800">{reg.reg_number}</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <Building size={14} className="text-primary-500 mt-0.5" />
                      <div>
                        <p className="text-[9px] font-bold text-gray-400 uppercase tracking-widest">Institution</p>
                        <p className="text-sm font-bold text-gray-800">{reg.institute}</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <Award size={14} className="text-primary-500 mt-0.5" />
                      <div>
                        <p className="text-[9px] font-bold text-gray-400 uppercase tracking-widest">Competition</p>
                        <p className="text-sm font-bold text-primary-600">{reg.competitions?.title || 'Unknown Event'}</p>
                      </div>
                    </div>
                  </div>
                </div>

                {/* QR Code */}
                <div className="flex-shrink-0 flex flex-col items-center">
                  <div className="p-3 bg-gray-50 rounded-2xl border-2 border-primary-50 mb-3 group transition-colors">
                    {qrUrl ? (
                      <img src={qrUrl} alt="QR Code" className="w-32 h-32 md:w-36 md:h-36 mix-blend-multiply" />
                    ) : (
                      <div className="w-32 h-32 bg-gray-200 animate-pulse rounded-lg" />
                    )}
                  </div>
                  <p className="text-[10px] font-bold text-gray-400 uppercase tracking-[0.15em] text-center">Entry Authorization</p>
                </div>
              </div>

              {/* Schedule / Footer info */}
              {schedule ? (
                <div className="bg-primary-50/50 p-8 border-t border-primary-50">
                  <div className="flex items-center gap-2 mb-4">
                    <Clock size={14} className="text-primary-500" />
                    <span className="text-[10px] font-black text-primary-700 uppercase tracking-widest">Event Timing & Venue</span>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="flex items-center gap-3">
                       <div className="w-8 h-8 rounded-lg bg-white shadow-sm flex items-center justify-center border border-primary-100 text-primary-600"><MapPin size={14}/></div>
                       <div>
                         <p className="text-xs font-bold text-gray-900">{schedule.rooms?.name}</p>
                         <p className="text-[10px] text-gray-400 font-medium">{schedule.rooms?.location}</p>
                       </div>
                    </div>
                    <div className="flex items-center gap-3">
                       <div className="w-8 h-8 rounded-lg bg-white shadow-sm flex items-center justify-center border border-primary-100 text-primary-600"><Calendar size={14}/></div>
                       <div>
                         <p className="text-xs font-bold text-gray-900">{schedule.time_slots?.label}</p>
                         <p className="text-[10px] text-gray-400 font-medium">{schedule.time_slots?.event_date}</p>
                       </div>
                    </div>
                  </div>
                </div>
              ) : (
                <div className="p-6 bg-yellow-50 text-center border-t border-yellow-100 italic">
                  <p className="text-yellow-700 text-[10px] font-bold uppercase tracking-widest">Schedule Announcement Pending</p>
                </div>
              )}

              {/* Verification Footer Strip */}
              <div className="bg-gray-50 px-8 py-3 flex justify-between items-center text-[10px] font-bold text-gray-400 border-t border-gray-100">
                <span className="uppercase tracking-widest flex items-center gap-1.5"><ShieldCheck size={12}/> Authorized Access</span>
                <span className="text-emerald-600 uppercase tracking-widest">Approved Pass</span>
              </div>
            </div>
          </motion.div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap gap-4 justify-center mb-16">
          <button 
            onClick={downloadCard} 
            className="btn-primary py-4 px-10 flex items-center gap-3 shadow-xl shadow-primary-200 group relative overflow-hidden"
          >
            <div className="absolute inset-0 bg-white/20 translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-700 skew-x-[25deg]"></div>
            <Download size={20} className="relative z-10" /> 
            <span className="relative z-10">Download / Print Pass</span>
          </button>
          <button onClick={logout} className="btn-outline py-4 px-8 flex items-center gap-2 hover:bg-red-50 hover:text-red-600 hover:border-red-200 font-bold transition-all">
            <LogOut size={18} /> Sign Out
          </button>
        </div>

        {/* On-Day Instructions */}
        <div className="max-w-lg w-full bg-white rounded-3xl border border-gray-100 p-8 shadow-sm">
           <div className="flex items-center gap-3 mb-6">
             <div className="w-9 h-9 bg-primary-50 text-primary-600 rounded-xl flex items-center justify-center shadow-inner"><ExternalLink size={20}/></div>
             <h3 className="font-black text-xl text-gray-900 tracking-tight">Event Day Checklist</h3>
           </div>
           <ul className="space-y-4 text-sm text-gray-500 font-semibold">
             {[
               "Provide this digital pass at the security gate and registration desk.",
               "Keep your CNIC or University Student ID for secondary verification.",
               "Reach your assigned room at least 15 minutes before the starting time."
             ].map((text, i) => (
               <li key={i} className="flex gap-4 items-start">
                 <span className="w-6 h-6 rounded-lg bg-primary-100/50 text-[11px] font-black text-primary-700 flex items-center justify-center flex-shrink-0 shadow-sm">{i+1}</span>
                 <p className="leading-relaxed">{text}</p>
               </li>
             ))}
           </ul>
        </div>
      </section>

      <Footer />
    </div>
  );
}